development:
  adapter: postgresql
  encoding: SQL_ASCII
  database: project_development
  pool: 8
  username: 
  password:

test:
  adapter: postgresql
  encoding: SQL_ASCII
  database: project_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: SQL_ASCII
  database: project_production
  pool: 8
  username: 
  password:

